### PR TITLE
Add PFNET_GRAPHVIZ env var flag, change names of raw-parser and line-flow env vars

### PR DESCRIPTION
**Pull request by awig**
checks for graphviz can be skipped by setting PFNET_GRAPHVIZ=OFF

changed names for directory environment variables of raw-parser and line-flow to PFNET_RAW_PARSER and PFNET_LINE_FLOW respectively.  

@ttinoco i checked with and without graphviz flag and with and without raw-parser directory set, but could not test with line-flow set of course

### CODE REVIEW

**Comment by ttinoco** [comment]
I thought we were only going to change the environment variables used by autotools/cmake to determine whether to build or where to find raw_parser, line_flow and graphviz, namely PFNET_GRAPHVIZ, PFNET_RAW_PARSER, PFNET_LINE_FLOW. Hence I was expecting 2 file changes (configure.ac and CMakeLists.txt), and minimal. However, I see 15 files have changed and I see that internal symbols have also been changed to have PFNET. I don't see a need for this.

**Comment by awig** [comment]
I misunderstood you then. That would have saved me some time. I'll change them all back

**Comment by awig** [comment]
updated for linux/macosx autotools builds, tested
still need to check cmake windows builds

**Comment by ttinoco** [comment]
Ok, thanks, don't forget to restore the tarball, and also to see why the CHANGELOG changed completely.

**Comment by awig** [comment]
@ttinoco done both of these. will let you know when I figure out the cmake issue for detecting the graphviz libraries before asking you to review again

**Comment by ttinoco** [comment]
Many thanks

**Comment by awig** [comment]
@ttinoco I think we should probably close this. Let me know?

**Comment by ttinoco** [comment]
I think we can close the PR but would be good to discuss what to do with
graphviz moving forward.

**Comment by awig** [comment]
Noted. Closing

**Pull request closed without merging**
