### PR TITLE
Updated Makefile to make to work for Mac OS X El Capitan

### PR DESCRIPTION
**Pull request by entriken**
You can delete the commented out duplicate lines.  We still need to decide how to handle the "-arch" flags on gcc.

### CODE REVIEW

**Comment by ttinoco** [comment]
Why are the changes in the makefile needed?  What problems did you have on "mac os x el capitan" with the original makefile?
In problem.c there are many "verbose" statements left in. I in general do not want to have these in the main code since they make it cluttered. In my opinion these pieces of code can be added during the debugging stage and then removed when an issue has been understood and solved (and a unittest added).

**Comment by entriken** [comment]
Dear Tomas,

Thank you for your questions.

pfnet/Makefile:

The including of -lpfnet in LDLIBS is a mistake that breaks on the first link of libpfnet.  That library is only needed for linking the tests, not for libpfnet itself, and I hard coded it there.  LDLIBS should be used for load libraries commonly needed for both libpfnet and tests.

I have include both i386 and x86_64 architectures in CFLAGS in order to ensure compatibility with both architectures in all libraries.  One day, i386 may no longer be needed.

pfnet/src/problem/problem.c

I have included the print statements for debugging, and I understand your concept about clutter.  Please consider that, in general, one person's clutter can be another person's gold.  These print statements are for both learning the code and for debugging, and on the Mac, with Eclipse, I do not yet have a working debugging environment, but I am working on it.

The value of the print statement at the beginning and end of each routine is for someone new to the code to learn the process flow.  I suppose I can write a script to add them automatically, if I really need to.

The value of the deeper statements is both to learn the process flow and to validate it.  It also includes prints to variable values.  In my case, I need to track the gradients and Hessians, and I need to track the form of the problem being solved.  The existing code does not have sufficiently convenient methods for printing its objects for validation purposes.  It may be best to add them, which may allow one to have fewer lines of unneeded print statements in the middle of the functions.

If you really want to have no such print statements in the master branch, it may be worthwhile to have an intermediate branch called debug (or something) that preserves these prints for learning and debugging purposes.

I hope this is helpful.

Sincerely,

Bob

Technical Executive
Electric Power Research Institute
3420 Hillview Avenue | Palo Alto, CA 94304
Tel: 650/855-2198 | Cell: 650/353-8956 | Fax: 650/855-2002
Email: rentrike@epri.com<mailto:rentrike@epri.com>

www.epri.com
Together...Shaping the Future of Electricity
________________________________

**Comment by ttinoco** [comment]
Thanks for the clarifications.
1) I will incorporate the makefile changes after trying on my computer. Next time it would be good to get a final version that I can just check and replace, without having to remove commented lines, etc (github shows the changes with respect to the original)
2) I only want minimal print statements or logging statements inside the code. These should be for logging important events such as errors. The bulk of the logging code should preferably be somewhere else and not mixed with the code. Using print statements to learn about the flow and debug is very useful and I use them all the time. However, once a piece of code is understood I think these statements can be removed. I would recommend using the logging Python module (https://docs.python.org/2/library/logging.html). In your fork you can create a "dev" branch where you can have code for debugging/understanding and a master branch that has this removed so I can review it and integrate it easily. I think that with the logging module debugging code can be made easy to find and remove automatically.

**Comment by ttinoco** [comment]
The Makefile suggestions were incorporated into the dev branch, except those with regards with architecture because the -arch flags gave me "undefined option" errors

**Pull request closed without merging**
