### PR TITLE
Added Network allocation, connectsiona and setters test

### PR DESCRIPTION
**Pull request by awig**
@ttinoco please review

### CODE REVIEW

**Comment by ttinoco** [comment]
@awig, thanks, but there is something wrong with the PR. There are 110 files that changed and lots of these changes (if not most) have already been included.

**Comment by awig** [comment]
@ttinoco it should be into dev not master.  editing this PR

**Comment by awig** [comment]
okay updated PR into dev

**Comment by ttinoco** [comment]
I am processing this. I have made some modifications/extensions. Will provide a summary soon.

**Comment by ttinoco** [comment]
Thanks @awig. It has been merged. 
Summary: The network-allocation-test branch has been merged into dev after the following updates:
- test was changed from single period to multi period
- asserts were eliminated and "compare_networks" utility was added at the end
- var generators and batteries were added to the original network
- var generators and batteries data was copied from original network
- var generator and battery bus setters were added (were missing in the python wrapper)
- bus.add_bat and bus.add_vargen were changed to add_battery and add_var_generator to be consistent with names in python wrapper
- shunt b_values allocation was added to python network creation test (@awig I recommend adding a raw file with switched shunts to python/data folder)
- fixed typo "orig_branh" (@awig I recommend adding a raw file that has tap changers to python/data folder)
- updated python network creation test to set component names (recently added to pfnet dev)
- updated python network creation test to set "pos_ratio_v_sens" of branches (@awig I recommend added raw case with tap changers to python/data)

**Comment by awig** [comment]
@ttinoco thanks for the improvements. i've added aeso case to the tests which has tap changers and switched shunts

**Comment by ttinoco** [comment]
ieee25 raw is also a good one to have

**Comment by awig** [comment]
i think it is already there. 

@ttinoco i'm also making changes to dev in order to get it working with [PFNET|GRIDOPT]/dev, i know this is just temporary until integration branch is done but it will at least give us a backup option

**Comment by ttinoco** [comment]
This is pfnet!

**Comment by awig** [comment]
i have brought shame upon myself

**Comment by awig** [comment]
we'll have to check on the legalize we need for any ieee or aeso cases

**Comment by ttinoco** [comment]
They are not in the repo. All raw files are ignored (gitignore)

**Pull request merged**
