### PR TITLE
Updated function calling line_flow

### PR DESCRIPTION
**Pull request by dmitry-shchetinin**
The C source and corresponding header were updated to make them work with the new version of `line_flow`. Note that since now it is possible to create an approximation of the line flow constraints at both ends of the branch simultaneously, `LF_construct` is now only used once per branch.

### CODE REVIEW

**Comment by ttinoco** [comment]
Awesome @dmitry-shchetinin I will review and merge. I will then add an option to gridopt ACOPF to use linearized line flow limits when available.

**Comment by ttinoco** [comment]
@dmitry-shchetinin I integrated line flow c and h files to pfnet and removed the checks in cmake and autotools build systems. I had to make some updates to line_flow c and h files. The reason is that TRUE/FALSE are already defined in PFNET, and also pfnet compilation is set to error for warnings and line_flow c/h where giving some warnings (e.g unused variables). I forked line_flow and will submit a PR with the updated line flow c and h files.  I updated the pfnet python module and all the unittests are passing. This updates are all in the pfnet branch "dmitry-master".

**Comment by ttinoco** [comment]
@dmitry-shchetinin I will ignore the last commit ("change dist"). The rest is good. I just need to make sure AC OPF with linear line flow constraints works as expected and then will close this PR.

**Comment by dmitry-shchetinin** [comment]
Thank you. I actually pushed it by accident, did not mean to. I ran AC OPF and it seems that the linear constraints are not working correctly. However, I currently do not have IPOPT as a solver in OPTALG, so I will run more tests once I install it.

**Comment by ttinoco** [comment]
Another comment: When you do a PR into pfnet from your fork, the convention is to first create a "topic branch" from your fork's dev branch (e.g. a new branch where the new features/fix is added), and then do a pull request for this topic branch of your fork into pfnet dev branch.

**Comment by dmitry-shchetinin** [comment]
Okay, got it!

**Comment by ttinoco** [comment]
Another comment: The nonlinear line flow constraints are i <= imax. In pfnet, they are converted to
f(x) = 0
l <= Gx <= u.
In this case, u happens to be imax. "l" in theory is not needed but pfnet requires it to be a number. Some options are -1e8 or 0 (because current magnitude is non-negative). However, I found that -1e8 is too loose and 0 is too tight. This was the cause of the issues we had before when solving AC OPF with nonlinear thermal limits (Remember IPOPT was failing?). What gave the best nonlinear solver performance was using l = -imax (not too loose, not too tight)

In the case of linearized line flow limits, we are using l <= Gx <= u, here G comes from line_flow's A and u comes from line_flow's b. For "l" we are using -1e8. My question is, can we use something more meaningful as in the nonlinear line flow constraints like l = -imax or l = -b? I do not know the exact contents of line_flow's Ax <= b. Let me know.

**Comment by dmitry-shchetinin** [comment]
I think it would be safer to use -1e8. In LineFlow, Ax<=b  represents a closed polytope so x is bounded anyway. Let us maybe check it with -1e8 first? I doubt that this can lead to numerical issues because these are linear constraints.

**Comment by ttinoco** [comment]
I suspect that it would not cause issues as in the nonlinear case. The
thing with the nonlinear case is that it requires slacks, and -1e8 provided
way too much flexibility and probably resulted in the algorithm exploring
some nonsensical slacks at the beginning and therefore getting stuck. I
agree, let's see if the performance is ok with -1e8

On Fri, Jan 26, 2018 at 8:43 AM, dmitry-shchetinin <notifications@github.com

**Comment by ttinoco** [comment]
Merged

**Pull request closed without merging**
